# Generated by Django 5.0.4 on 2024-11-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokom", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="stock",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
