# Generated by Django 5.0.4 on 2024-11-19 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tokom", "0002_alter_item_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="id",
            new_name="item_id",
        ),
    ]
