# Generated by Django 5.1 on 2024-11-23 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokom', '0003_rename_id_item_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='items/'),
            preserve_default=False,
        ),
    ]
