# Generated by Django 5.0.4 on 2024-11-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokom", "0005_rename_id_review_review_id_alter_order_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
