# Generated by Django 5.1 on 2024-11-26 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokom', '0005_rename_id_review_review_id_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='reviews/'),
            preserve_default=False,
        ),
    ]
