# Generated by Django 5.0.4 on 2024-11-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokom", "0006_alter_item_description_alter_order_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
