# Generated by Django 5.1 on 2024-11-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokom', '0007_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
