# Generated by Django 5.1 on 2024-11-27 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokom', '0008_alter_review_image'),
        ('tokom', '0009_orderdetails_delete_orderdetail'),
    ]

    operations = [
    ]
