# Generated by Django 5.0.4 on 2024-11-28 01:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokom", "0013_review_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_arrived",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
