# Generated by Django 5.1 on 2024-11-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokom', '0015_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('arrived', 'Arrived')], default='Ongoing', max_length=10),
        ),
    ]
